version: '3'

services:
  orders_api:
    container_name: orders_api
    image: openjdk:17-jdk-slim
    ports:
      - 8080:8080
    volumes:
      - ./jar:/app
    working_dir: /app
    command: ["java", "-jar", "asiayo_test-0.0.1-SNAPSHOT.jar"]

